Nodejs week2
TatjanaOcedova/hyf-homework pull request #19
Opened 2022-04-08 18:46 UTC by TatjanaOcedova

Add homework Nodejs week2

2022-04-10 21:45 UTC, Divyajg requested changes
Good work @TatjanaOcedova . 
I can see a bit of confusion in your code. I have suggested a few things. Please make changes.
Let me know If you have any questions.

2022-04-10 21:45 UTC, Divyajg commented on nodejs/week2/homework/meal-sharing/src/backend/api/meals-router.js
> +   filterDate = meals.filter((item => new Date(item.createdAt) > new Date(createdAfter)))
I would use Date.parse(createdAfter) as it calculates the time between two dates in milliseconds and compare them, while new Date() returns an object.
new Date() can be used when the date need to record. for example when creating a meal, we use new Date().
[for more info](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse)

2022-04-10 21:45 UTC, Divyajg commented on nodejs/week2/homework/meal-sharing/src/backend/api/meals-router.js
> +   }
What if the array filterDate is empty?
You need to write another query `if(filterDate===[]){
return response.status(200).send("no meals available");
}` here response code is 200 because the meals are successfully filtered as per the query.

2022-04-10 21:45 UTC, Divyajg commented on nodejs/week2/homework/meal-sharing/src/backend/api/meals-router.js
> +    filterLimit = meals.filter(item => item.id <= limit)
item.id and limit can be numbers but not same.
What if your item.id starts with 101 and you gave limit 5? we expect to filter the first 5 items. But your code will return an empty array.
You can use slice method or for loop with the meals.length property.

2022-04-10 21:45 UTC, Divyajg commented on nodejs/week2/homework/meal-sharing/src/backend/api/meals-router.js
> +  }
your code will return two arrays with query requests and also the meals. 
if statements for query requests should be used inside this try method.

2022-04-10 21:45 UTC, Divyajg commented on nodejs/week2/homework/meal-sharing/src/backend/api/meals-router.js
> +  try {
What if there are more than one request Query?

2022-04-10 21:45 UTC, Divyajg commented on nodejs/week2/homework/meal-sharing/src/backend/api/meals-router.js
> +      return response.json(filterPrice)
What if the filterPrice is an empty array?

2022-04-10 21:45 UTC, Divyajg commented on nodejs/week2/homework/meal-sharing/src/backend/api/meals-router.js
> +    response.status(400).json("There is no meal with the requested id")
This condition checks, whether the given parameter is an integer or not?
It doesn't check whether the given parameter is a valid mealId or not!

-

2022-04-10 21:45 UTC, Divyajg commented on nodejs/week2/homework/meal-sharing/src/backend/api/meals-router.js
> +  }
What if there is no meal with given Id?

2022-04-10 21:45 UTC, Divyajg commented on nodejs/week2/homework/meal-sharing/src/backend/api/reservations-router.js
> +  if (!Number.isInteger(reservationId)) {
This condition checks, whether the given parameter is an integer or not?
It doesn't check whether the given parameter is a valid reservation Id or not!

2022-04-10 21:45 UTC, Divyajg commented on nodejs/week2/homework/meal-sharing/src/backend/api/reservations-router.js
> +  }
You can try to make a condition if the newReservation is empty, then response should be 400 and reservation with id is not found.

2022-04-10 21:45 UTC, Divyajg commented on nodejs/week2/homework/meal-sharing/src/backend/api/reviews-router.js
> +    response.status(400).json("There is no review with the requested id")
It's not that, the above condition is wrong. But it needs more specificity.

2022-04-10 21:45 UTC, Divyajg commented on nodejs/week2/homework/meal-sharing/src/backend/api/reviews-router.js
> +  })
You check for that like
`if(object.keys(newReview)===0){response.status(400).json("There is no review with the requested id")}else{response.send(newReview)}`

2022-04-20 10:56 UTC, TatjanaOcedova commented on nodejs/week2/homework/meal-sharing/src/backend/api/meals-router.js
> +   }
I try but is not working

2022-04-20 10:58 UTC, TatjanaOcedova commented on nodejs/week2/homework/meal-sharing/src/backend/api/meals-router.js
> +  try {
I can write more requests but it only shows results by one request.

2022-04-20 11:01 UTC, TatjanaOcedova commented
Thank you for the great review. I made some changes if you can check and I still have some questions.

2022-04-30 08:24 UTC, merged